services:
  database:
    image: mariadb:10
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .db.env
    networks:
      - actionsNetwork

  redis:
    image: redis:7-alpine
    container_name: rediscontainer
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - actionsNetwork

  server:
    container_name: actionscontainer
    image: actions-server
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: database
      REDIS_HOST: redis
    env_file:
      - .env
    depends_on:
      - database
      - redis
    networks:
      - actionsNetwork

networks:
  actionsNetwork:
    driver: bridge
